services:
  db:
    environment:
      - MYSQL_ROOT_PASSWORD
    image: mysql:8.0
    restart: always
    volumes:
      - ./data-db:/var/lib/mysql

  proxy:
    environment:
      - GHOST_PUBLIC_URL_A
      - GHOST_PUBLIC_URL_B
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    restart: always
    secrets:
      - ssl_certificate
      - ssl_certificate_key
    volumes:
      - ./templates:/etc/nginx/templates:ro

  site-a:
    depends_on:
      - db
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - database__connection__database=site-a
      - url=https://${GHOST_PUBLIC_URL_A:?err}
    image: ghost:5
    restart: always
    volumes:
      - ./data-site-a:/var/lib/ghost/content

  site-b:
    depends_on:
      - db
    environment:
      - database__client=mysql
      - database__connection__host=db
      - database__connection__user=root
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - database__connection__database=site-b
      - url=https://${GHOST_PUBLIC_URL_B:?err}
    image: ghost:5
    restart: always
    volumes:
      - ./data-site-b:/var/lib/ghost/content

secrets:
  ssl_certificate:
    file: ./secrets/fullchain.pem
  ssl_certificate_key:
    file: ./secrets/privkey.pem
