services:
  ghost:
    depends_on:
      - ghost-db
    environment:
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - database__connection__database=ghost
      - url=https://${GHOST_PUBLIC_URL:?err}
    image: ghost:5
    restart: always
    volumes:
      - ./data:/var/lib/ghost/content

  ghost-db:
    environment:
      - MYSQL_ROOT_PASSWORD
    image: mysql:8.0
    restart: always
    volumes:
      - ./data-db:/var/lib/mysql

  ghost-proxy:
    image: nginx:stable
    ports:
      - "80:80"
      - "443:443"
    restart: always
    secrets:
      - ssl_certificate
      - ssl_certificate_key
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d:ro

secrets:
  ssl_certificate:
    file: ./secrets/${GHOST_PUBLIC_URL:?err}.crt
  ssl_certificate_key:
    file: ./secrets/${GHOST_PUBLIC_URL:?err}.key
