services:
  ghost:
    depends_on:
      - ghost-db
    environment:
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=root
      - database__connection__password=${MYSQL_ROOT_PASSWORD:?err}
      - database__connection__database=ghost
      - url=http://localhost
    image: ghost:5.17.1
    restart: always
    volumes:
      - ./data:/var/lib/ghost/content

  ghost-db:
    environment:
      - MYSQL_ROOT_PASSWORD
    image: mysql:8.0.30
    restart: always
    volumes:
      - ./data-db:/var/lib/mysql

  ghost-proxy:
    image: nginxinc/nginx-unprivileged:1.22.0
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d:ro
